// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYdzqYwyNODIRHn11w1uZAUiAtxChGSY',
    appId: '1:422701510515:web:7a6f5da9073ae868b35f06',
    messagingSenderId: '422701510515',
    projectId: 'storeapp-37369',
    authDomain: 'storeapp-37369.firebaseapp.com',
    databaseURL: 'https://storeapp-37369-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-37369.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtr6tvpUL-_AQYzKWR8b8by78200QX-pI',
    appId: '1:422701510515:android:8cd5da06894b9274b35f06',
    messagingSenderId: '422701510515',
    projectId: 'storeapp-37369',
    databaseURL: 'https://storeapp-37369-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-37369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqY65jG6JQjmozX3p34IQw9A7W1joqP2s',
    appId: '1:422701510515:ios:caaca2cbf5d93df7b35f06',
    messagingSenderId: '422701510515',
    projectId: 'storeapp-37369',
    databaseURL: 'https://storeapp-37369-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-37369.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.jatoloza.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqY65jG6JQjmozX3p34IQw9A7W1joqP2s',
    appId: '1:422701510515:ios:caaca2cbf5d93df7b35f06',
    messagingSenderId: '422701510515',
    projectId: 'storeapp-37369',
    databaseURL: 'https://storeapp-37369-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-37369.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.jatoloza.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkYdzqYwyNODIRHn11w1uZAUiAtxChGSY',
    appId: '1:422701510515:web:54172d389a6d4720b35f06',
    messagingSenderId: '422701510515',
    projectId: 'storeapp-37369',
    authDomain: 'storeapp-37369.firebaseapp.com',
    databaseURL: 'https://storeapp-37369-default-rtdb.firebaseio.com',
    storageBucket: 'storeapp-37369.firebasestorage.app',
  );

}